FROM node:lts-alpine3.22

ARG FIREBIRDAPI_VERSION=v1.0.3
ARG FIREBIRDAPI_USER=SYSDBA
ARG FIREBIRDAPI_PASSWORD=masterkey
ARG FIREBIRDAPI_ENCODING=win1252
ARG FIREBIRDAPI_READONLY=true
ARG FIREBIRDAPI_CORS_ALLOW_SERVER_TO_SERVER_ACCESS=true
ARG FIREBIRDAPI_CORS_WHITELIST='["*"]'
ARG PORT=3000
ARG NODE_FIREBIRD_ENCODING=LATIN1
ARG FIREBIRD_DB_HOST=127.0.0.1
ARG FIREBIRD_DB_PORT=3050
ARG FIREBIRD_DB_PAGESIZE=4096
ARG FIREBIRD_DB_ENCODING=NONE

ENV FIREBIRDAPI_VERSION=$FIREBIRDAPI_VERSION
ENV FIREBIRDAPI_USER=$FIREBIRDAPI_USER
ENV FIREBIRDAPI_PASSWORD=$FIREBIRDAPI_PASSWORD
ENV FIREBIRDAPI_ENCODING=$FIREBIRDAPI_ENCODING
ENV FIREBIRDAPI_READONLY=$FIREBIRDAPI_READONLY
ENV FIREBIRDAPI_CORS_ALLOW_SERVER_TO_SERVER_ACCESS=$FIREBIRDAPI_CORS_ALLOW_SERVER_TO_SERVER_ACCESS
ENV FIREBIRDAPI_CORS_WHITELIST=$FIREBIRDAPI_CORS_WHITELIST
ENV PORT=$PORT
ENV NODE_FIREBIRD_ENCODING=$NODE_FIREBIRD_ENCODING
ENV FIREBIRD_DB_HOST=$FIREBIRD_DB_HOST
ENV FIREBIRD_DB_PORT=$FIREBIRD_DB_PORT
ENV FIREBIRD_DB_PAGESIZE=$FIREBIRD_DB_PAGESIZE
ENV FIREBIRD_DB_ENCODING=$FIREBIRD_DB_ENCODING

EXPOSE $PORT

RUN apk update && apk add git bash
RUN mkdir /app
WORKDIR /app
RUN git clone -c advice.detachedHead=false --single-branch -b $FIREBIRDAPI_VERSION https://github.com/ACP-Sistemas/firebird-api
WORKDIR /app/firebird-api
RUN npm install
COPY "./entrypoint.sh" "/app"
RUN chmod +x "/app/entrypoint.sh"
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["npm", "start"]
